### ISSUE TITLE
Consider eval/bquote for model formulae

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#14]
When testing the new `mc_fit_comp()` function in the Shiny app, I ran into some problems that I couldn't figure out until I realized I wasn't passing the right variables. Part of my confusion was that the VGAM::vglm model object had only `formula = formula` which is fine if no one will ever look at it, but a bit of a black box otherwise.

While this isn't really a major issue, perhaps consider using the `bquote()` and `eval()` functions to make sure the formula gets evaluated before evaluating the model itself?

E.g.:

```
m <- eval(bquote(
    VGAM::vglm(
      formula=.(formula),
      data=x_srv,
      family=VGAM::multinomial,
      na.action=stats::na.omit)))
```

So that `mc_fit_comp(x, "Fire8212_DEM815")` would yeild (for example):
```
Call:
VGAM::vglm(formula = ymat ~ Fire8212_DEM815, family = VGAM::multinomial, 
    data = x_srv, na.action = stats::na.omit)
```

What do you think? I could open another pull request?

**Comment by psolymos** [comment]
Yes, this makes sense, thanks for the suggestion. This could be important when using the call to `update()` the model etc. VGAM otherwise is quite finicky, lots of namespace issues if you don't want to include in `Depends`. Thanks.

**Comment by steffilazerte** [comment]
Okay, I learned that it is really hard to make a new branch that doesn't have the commits already on my main branch, so perhaps I'll leave this to you? 😅

**Comment by psolymos** [comment]
Sure, no problem!

**Comment by psolymos** [comment]
I just used `m@call$formula <- formula` :)
