### ISSUE TITLE
Error in dimnames(X.vlm) with mc_predict_comp()

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#18]
Hi @psolymos,  this might be the result of making silly, random models, but on occasion, I get the following error when trying to calculate the composition prediction intervals. This time I took note of the actual models so I could reproduce the problem.

Worth fixing?

``` r
library(moosecounter)
#> This is moosecounter 0.5-1    2022-01-31

## modify options as needed
mc_options(B=20)

## load/read data set
x <- read.csv(system.file("extdata", "UKH2017_MMU_Querried_data_for_Analysis_Final_3.csv", package = "moosecounter"))
switch_response("total")
x <- mc_update_total(x)

# Total models
ML <- list()
ML[["A"]] <- mc_fit_total(x, c("MMU_ID", "AllNeedleWet", "LKStrat_01", "DEM800to1200m"),
                          dist="NB", weighted = FALSE)
ML[["B"]] <- mc_fit_total(x, c("MMU_ID", "AllNeedleWet", "LKStrat_01", "DEM800to1200m"),
                          zi_vars = c("DEM800to1200m", "Fire1982to2012", "NALC_DesShrMix"),
                          dist = "NB", weighted = FALSE)

# Comp models
mc_check_comp(x)
CML <- list()
CML[["A"]] <- mc_fit_comp(x, vars = c("DEM800to1200m", "Fire1982to2012", "NALC_DesShrMix"))

# Error
CPI <- mc_predict_comp(
  total_model_id = c("A", "B"),
  comp_model_id = "A",
  model_list_total = ML,
  model_list_comp = CML,
  x=x,
  do_avg=TRUE)
#> Loading required namespace: shiny
#> Error in dimnames(X.vlm) <- list(vlabel(yn, rep(M, nrow.X.lm), M), vlabel(xn, : length of 'dimnames' [1] not equal to array extent
```

<sup>Created on 2022-03-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by psolymos** [comment]
Could be because `"MMU_ID"` and `"LKStrat_01"` are categorical and bootstrapping might lead to levels being dropped. In that case the coefs won't match. `"MMU_ID"` as a covariate might not make much sense, but this can happen to other potential predictors, so I'll check. Thanks for the reprex!

**Comment by psolymos** [comment]
It turns out, it has nothing to do with categorical variables. Composition is conditional on >0 total moose, and certain subsets had no moose...
