### ISSUE TITLE
mc_plot_predpi() should use best model as title when do_avg = FALSE

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#2]
In `mc_plot_predpi()` the model title is taken to be "Avg" if more than one model is used.
However, if I understand correctly, when `do_avg = FALSE`, only one of the multiple models is used and therefore, that should be the title.

Therefore, I think line 444 in total.R
https://github.com/psolymos/moosecounter/blob/1307d10432c47bb97a55ddb998c35aff72b8e481/R/total.R#L444-L446

should be:
```
  ModID <- unique(PI$model_select_id)
```

Make sense? Should I change this on my end?

**Comment by psolymos** [comment]
I'll add this to my recent PR #3 thanks!

**Comment by psolymos** [comment]
This is how it should be:

```R
    ModID <- if (length(PI$model_id)>1)
        "Avg" else unique(PI$model_select_id)
```

**Comment by steffilazerte** [comment]
Should it be using `unique(PI$model_select_id)` in the condition? Otherwise, if I choose the option of `do_avg = FALSE`, I still get "Avg" in the title, whereas I think it would be better if it told you which model was the best and that it was showing. Or have I misunderstood what it means when `do_avg = FALSE`?

```
  ModID <- if (length(unique(PI$model_select_id))>1)
        "Avg" else unique(PI$model_select_id)
```

**Comment by psolymos** [comment]
The `PI$model_select_id` element is a vector of length B (bootstrap runs from options), when we do averaging we pick a random model ID based on the likelihood weights. So when there is only 1 model ID provided, or when B is small or the weight for one models is ~1 (it gets picked always), we get `length(unique(PI$model_select_id))==1`. When there is no other model involved in the *actual* results, we can print the model ID. When `length(unique(PI$model_select_id))>1` we can print the most frequent, or just say `"Avg"`.

In case of `do_avg = FALSE` we use the same model ID over and over again, which means that all the B values in `PI$model_select_id` will be identical, but the length is still B.

**Comment by steffilazerte** [comment]
Right, so isn't that why we should use the unique values of `model_select_id`, and not `model_id`? Because if you give the function two models, and say `do_avg = FALSE`, then it only uses one model, but `model_id` still contains two values...?

**Comment by psolymos** [comment]
Yes, that's correct. `model_id` stores the input, `model_select_id` stores the actual used values.

So I guess the question is: when `model_id` has > 1 element, should we say `"Avg"` even when `model_select_id` has only 1 unique value.

My suggested solution returns the model ID even if `length(model_id)>1` but `length(unique(model_select_id))==1`.

**Comment by steffilazerte** [comment]
For me, I don't like "Avg", if the option was to NOT average. I think it might cause confusion (it confused me, making me think I had misspecified the arguments).

Perhaps a more informative title?

1. One `model_id`-> "`model_id`"
2.  Two+ `model_id`s AND `do_avg = TRUE` -> "Avg"
3. Two+ `model_id`s AND `do_avg = FALSE` -> "Best Model: `unique(model_select_id)`"

Does that make sense?

**Comment by steffilazerte** [comment]
Wait... 

> My suggested solution returns the model ID even if length(model_id)>1 but length(unique(model_select_id))==1.

It does? I get Avg in this situation, which is why I'm confused :D

**Comment by psolymos** [comment]
OK, here is an example:

```R
library(moosecounter)
set.seed(1)
mc_options(B=20)
x <- read.csv("inst/extdata/MayoMMU_QuerriedData.csv")
switch_response("total")
x <- mc_update_total(x)
vars <- c("ELC_Subalpine", "Fire1982_2012", "Fire8212_DEM815",
    "NALC_Needle", "NALC_Shrub", "Subalp_Shrub_250buf",
    "ELCSub_Fire8212DEM815", "SubShrub250_Fire8212DEM815")
ML <- list()
ML[["Model 0"]] <- mc_fit_total(x, dist="ZINB", weighted=TRUE)
ML[["Model 1"]] <- mc_fit_total(x, vars[1:2], dist="ZINB", weighted=TRUE)
ML[["Model 2"]] <- mc_fit_total(x, vars[2:3], dist="ZIP", weighted=TRUE)
ML[["Model 3"]] <- mc_fit_total(x, vars[3:4], dist="ZINB", weighted=TRUE)

PI <- mc_predict_total(
    model_id=c("Model 1", "Model 3"),
    ml=ML,
    x=x,
    do_boot=TRUE, do_avg=TRUE)
table(PI$model_select_id)
# Model 1 Model 3 
#       2      18 
if (length(unique(PI$model_select_id))>1)
    "Avg" else unique(PI$model_select_id)
# [1] "Avg"

PI <- mc_predict_total(
    model_id=c("Model 1", "Model 3"),
    ml=ML,
    x=x,
    do_boot=TRUE, do_avg=FALSE)
table(PI$model_select_id)
# Model 3 
#      20 

if (length(unique(PI$model_select_id))>1)
    "Avg" else unique(PI$model_select_id)
# [1] "Model 3"
```

Do you want to chat?
