### ISSUE TITLE
Crosstalk-like behaviour on Univariate plots

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#22]
I think I've got this covered by using patchwork with the ggiraph plots.

For example
- https://albert-rapp.de/posts/ggplot2-tips/17_ggiraph/17_ggiraph.html#combine-ggirafe-and-patchwork
- https://allisonhorst.github.io/ggiraph-demo/demo.html

To do this I have made the following changes: 
- Switched the data_id arguments to the Point ID to allow this linking to work
- moved the `ggiraph::girafe()` call to a separate function (so we can patchwork them together first)
- Tweaked the css styling to work with all types of plots (fit, map, density; categorical or continuous)
- Added transparency to the map for surveyed vs. not surveyed (to explain why not all points in the 'fit' plot are highlighted when selecting a map cell)
- Tweaked the colour for the categorical maps to match that of the density plots

**Comment by steffilazerte** [comment]
Do we want to add an overlay of points to the categorical boxplots? That way all the surveyed points on the map can be highlighted in the fit plot...

![image](https://github.com/psolymos/moosecounter/assets/14676081/2a400bdc-2c0e-42cb-9199-fb0b530e4a43)

**Comment by psolymos** [comment]
Yes, the overlay is a good idea!

**Comment by steffilazerte** [comment]
There are points overlaid on the boxplot now, jittered so they're actually selectable.

I think I'm done with this aspect, unless you have something else I should tweak?

![image](https://github.com/psolymos/moosecounter/assets/14676081/02416384-566a-4695-a6b3-07b3693fbde4)

**Comment by psolymos** [comment]
This looks good. Thanks!
