### ISSUE TITLE
Histogram binning

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#24]
**To do:**
> For the histogram predicting the total population, would it possible to specify the number of bins? Sometimes the graph is very ugly

**Question:**
There are a few histograms, should there be options to adjust the bin widths for all of these?
If not, which ones are the ones should be fixed? Just the Prediction Intervals `mc_plot_pidistr()`?

Histograms: 
- `mc_plot_residuals()` (in the `total_resid_plot` output for the model residuals)
- `mc_plot_predpi()` (in the `total_pi_predpi` output for the prediction intervals) [almost the same as `mc_plot_residuals()`]
- `mc_plot_pidistr()` (from the Total Moose PI and the Cell Level PI)

<img src = "https://github.com/psolymos/moosecounter/assets/14676081/1e028ae9-ed5e-48f2-9da6-363afb97fe84" height = 200>
<img src = "https://github.com/psolymos/moosecounter/assets/14676081/804a48f7-0008-4839-a157-4a143eee5d33" height = 200>

**Comment by psolymos** [comment]
The residual plot does not need to be tweaked (the bins match the colors in the map-like scatter plot).

This task relates to the PI histogram.

**Comment by steffilazerte** [comment]
So we now have a slider bar to select the number of bins for the total PI histograms and the cell-level histograms.

![image](https://github.com/psolymos/moosecounter/assets/14676081/c9116b0e-a791-440b-b8aa-b2c84e433d4d)
![image](https://github.com/psolymos/moosecounter/assets/14676081/ee2120a3-1c11-4923-b02a-773d159cad2d)

A couple of things to consider: 
- The limits are hard coded (maybe they shouldn't be?)
- We could centre the slider above the plot, but I found it look a bit out of place
- Putting the slider above the plot makes the plots somewhat wider, but I'm not really sure how to improve this. 
- We could put the input to the left of the plot
    - We could use a more narrow input and put it next to the plot
    - We could put the slider next to the plot and just let it be wide
    - But inline alignment is always a bit weird

**Comment by psolymos** [comment]
Thanks. Some thoughts below.

>  The limits are hard coded (maybe they shouldn't be?)

This is all right. I don't think we'll ever need more than 100.

>    We could centre the slider above the plot, but I found it look a bit out of place
>    Putting the slider above the plot makes the plots somewhat wider, but I'm not really sure how to improve this.

Above the plot to the left is perfect.

>    We could put the input to the left of the plot
>        We could use a more narrow input and put it next to the plot
>        We could put the slider next to the plot and just let it be wide
>        But inline alignment is always a bit weird

We can use a numeric input instead of a slider, but the slider is a bit more intuitive, so let's leave it as is.

**Comment by steffilazerte** [comment]
Okay, so I'll leave this as is, let me know if you need any tweaks!

**Comment by psolymos** [comment]
Thanks!
