### ISSUE TITLE
Plot image download issues

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#26]
### The problem:
> There is one issue that we actually really need fixed and it sounds like it’s a Mac/Windows issue. We are not able to use the download tool for all the graphs and plots (in the Total and Composition tabs) so the only thing we can do is screenshot. Ideally, it would be great to download (or even copy/paste) individual graphs/plots.

- Test download functionality in Chrome/Firefox/Safari (Mac) and Chrome/Firefox/Safari/Edge on Windows
- Likely need to add download button using plotly::export() https://github.com/plotly/plotly.R/issues/672

### Solutions for plotly
Amusingly, if you look at `?export`, it says "deprecated, use `orca()`", which says "superseded, use `kaleido()`" which requires `reticulate`, which, less amusing, requires bit of installing: 
> install.packages('reticulate')
> reticulate::install_miniconda()
> reticulate::conda_install('r-reticulate', 'python-kaleido')
> reticulate::conda_install('r-reticulate', 'plotly', channel = 'plotly')
> reticulate::use_miniconda('r-reticulate')

### Solutions for ggiraph, etc.
However...  what functions actually use plotly? I thought they were all ggiraph/ggplot2 or base plots? 

- Is the problem with the Save to Png button in ggiraph?
- older browsers seem to have a problem (https://www.ardata.fr/ggiraph-book/toolbar.html#download-button)
- is it a javascript issue?
- Possibly, there was a bug, but that was in a pretty old version: https://github.com/davidgohel/ggiraph/issues/138

@psolymos Do you use windows/mac? Do you have problems? (I can dual boot, but would have to spend sometime getting it setup, so if you have it, I'll let you check 😁 )

Worst case scenario, I think we should be able to capture and save the ggplot2 plots before they are returned as interactive ggiraph plots

**Comment by psolymos** [comment]
Let me test this. I have had no issues. But I can imagine that gov laptops might not be on the bleeding edge ...

**Comment by psolymos** [comment]
@steffilazerte it looks like that not all ggiraph plots have the download icon in the corner (e.g. the univariate exploration does not have it). Moreover, the base plots can be saved with right click and "save image as" from the browser.

Do you think we could implement a base graphics / ggplot download functionality where the files would have more meaningful names (i.e. not `untitled.png`)? This could be paired with a little download button with only the download icon next to the plots.

We'd need to have functions that produce the plots and then the download can call these, `png()` or `ggsave()` would write the files. Same function can be called by the render function can. Some plots are already like this.

Let me know what you think.

**Comment by steffilazerte** [comment]
So the idea would be to have a the ggiraph download icon always available and if not a ggiraph plot, then have a download plot button? I think I've done that before, a bit fiddly, but definitely doable. I'll take a look!

**Comment by psolymos** [comment]
I had a call today to clarify the issue: the ggiraph download button is not working on their end, and would be good to have the download option for the base graphs too.

**Comment by steffilazerte** [comment]
Okay so have a download button for all plots, ggiraph and base, got it.

**Comment by steffilazerte** [comment]
First pass is going pretty well. I have a working button for both the ggiraph Univariate plot and the base plot Multivariate plot. 
- The button is disabled by default
- The button is enabled when the plot reactive is ready
- The button will re-disable if the plot reactive becomes un-ready (if the variables are unselected, for example)
- The plot name reflects the plot (but nothing else right now)
- There is a download message which pops up while a plot is being prepared for downloading

How have I never heard of `recordPlot()` and `replayPlot()` before!?!?!?!?!

What do you think? Suggestions or tweaks before I apply this to the rest of the plots?

I assume I should apply this to all the plots (including residuals, etc.), or are there some which really don't need it?

![image](https://github.com/psolymos/moosecounter/assets/14676081/c0a67874-c72a-4697-ad39-3839eff290f6)

**Comment by psolymos** [comment]
Thanks @steffilazerte . I am in the mountains for the weekend, I will check on Tuesday. If you want to proceed with this before then I'll leave it up to you. But it looks pretty nice :)

**Comment by psolymos** [comment]
Hi @steffilazerte please go ahead and apply this to the rest of the plots. Thanks!

**Comment by steffilazerte** [comment]
Okay, I think we're good to go here!

- I added the download button to all plots
- I tweaked the ggiraph renders to use the same `mc_ggiraph()` function so we can adjust the plot settings in one place

The plot file names could be more informative, right now they match the Shiny reactive names.
