### ISSUE TITLE
"Brent" is only available for one-dimensional optimization 

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#5]
When playing around with different optimization methods, I get

`Error in stats::optim(fn = loglikfun, gr = gradfun, par = c(start$count, : method = "Brent" is only available for one-dimensional optimization`

for the "Brent" option, should we omit this as an option since none of the modelling the app does is one-dimensional?

**Comment by psolymos** [comment]
Yes! Thanks for flagging this. I checked the rest and those should be fine for multivariate optimization.
