### ISSUE TITLE
Multivariate exploration with only one variable looks funny

### ISSUE THREAD

**Issue by steffilazerte** [psolymos/moosecounter#8]
@psolymos should I make it so the multivariate figure only shows if there are more than two variables?  When there is only one we get weird `x...vars` labels. Is this okay and/or expected?

![image](https://user-images.githubusercontent.com/14676081/134405208-6f0755da-bc5f-4daf-ba8a-4f798358cf0b.png)

**Comment by psolymos** [comment]
@steffilazerte 1 variable should be fine (contrary to the tab name), I'll check what is going on with the colnames. Could be a `drop=FALSE` issue somewhere.

**Comment by psolymos** [comment]
We have this: `z <- data.frame(Y=x[[opts$Ntot]], x[,vars])[x$srv,]`, I suspect `z <- data.frame(Y=x[[opts$Ntot]], x[,vars,drop=FALSE])[x$srv,]` should work.
